In [1]:
import numpy as np

In [2]:
naming = [1,2,3,4,5,6]
cat2_dict ={"развитая": 0.8, "средняя": 0.6}
cat3_dict ={"сомнительная": 0.2, "средняя": 0.6, "хорошая": 0.8}
category1 = [5, 2, 6, 5, 7, 4]
category2 = [cat2_dict["развитая"], cat2_dict["развитая"],
             cat2_dict["развитая"],cat2_dict["средняя"],
             cat2_dict["средняя"]-0.05, cat2_dict["средняя"] + 0.05]
category3 = [cat3_dict["сомнительная"], cat3_dict["хорошая"],
             cat3_dict["средняя"], cat3_dict["хорошая"],
             cat3_dict["средняя"], cat3_dict["хорошая"]]

decision_matrix = np.array([naming, category1, category2, category3])
print(decision_matrix)
decision_matrix = decision_matrix.T
print(decision_matrix)

[[1.   2.   3.   4.   5.   6.  ]
 [5.   2.   6.   5.   7.   4.  ]
 [0.8  0.8  0.8  0.6  0.55 0.65]
 [0.2  0.8  0.6  0.8  0.6  0.8 ]]
[[1.   5.   0.8  0.2 ]
 [2.   2.   0.8  0.8 ]
 [3.   6.   0.8  0.6 ]
 [4.   5.   0.6  0.8 ]
 [5.   7.   0.55 0.6 ]
 [6.   4.   0.65 0.8 ]]


In [3]:
print(decision_matrix.shape)
isOkey = False
while not isOkey:
    isOkey = True
    for i in range(decision_matrix.shape[0]):
        if isOkey == False:
            break

        for j in range(decision_matrix.shape[0]):
            if(i == j):
                continue
            f_row = decision_matrix[i]
            s_row = decision_matrix[j]
            
            better_count = 0
            
            for k in range(1, len(f_row)):
                if f_row[k] >= s_row[k]:
                    better_count +=1

            if better_count == len(f_row)-1:
                print('delete', s_row)
                decision_matrix = np.delete(decision_matrix, j, 0)
                isOkey = False
                break

print(decision_matrix)

(6, 4)
delete [1.  5.  0.8 0.2]
[[2.   2.   0.8  0.8 ]
 [3.   6.   0.8  0.6 ]
 [4.   5.   0.6  0.8 ]
 [5.   7.   0.55 0.6 ]
 [6.   4.   0.65 0.8 ]]


In [4]:
eksprt1 = np.array([7,6,9])
eksprt2 = np.array([6,8,9])

eksprt_sum = eksprt1 + eksprt2
sum_of_rating = np.sum(eksprt_sum)
print(eksprt_sum, sum_of_rating)
w = eksprt_sum / sum_of_rating
print(w, np.sum(w))

[13 14 18] 45
[0.28888889 0.31111111 0.4       ] 1.0


In [5]:
c = np.zeros((decision_matrix.shape[0],decision_matrix.shape[0]))
for i in range(decision_matrix.shape[0]):
    for j in range(decision_matrix.shape[0]):
        if(i == j):
            c[i][j] = 1
            continue
        f_row = decision_matrix[i]
        s_row = decision_matrix[j]
        
        betters_indexs = []
        for k in range(1, len(f_row)):
            if f_row[k] >= s_row[k]:
                betters_indexs.append(k-1)
        
        for k in betters_indexs:
            c[i][j] += w[k]

print(c)

[[1.         0.71111111 0.71111111 0.71111111 0.71111111]
 [0.6        1.         0.6        0.71111111 0.6       ]
 [0.68888889 0.4        1.         0.71111111 0.68888889]
 [0.28888889 0.68888889 0.28888889 1.         0.28888889]
 [0.68888889 0.4        0.71111111 0.71111111 1.        ]]


In [6]:
d = np.zeros((decision_matrix.shape[0],decision_matrix.shape[0]))
for i in range(decision_matrix.shape[0]):
    for j in range(decision_matrix.shape[0]):
        if(i == j):
            continue
        f_row = decision_matrix[i]
        s_row = decision_matrix[j]
        
        worstes_indexs = []
        for k in range(1, len(f_row)):
            if f_row[k] < s_row[k]:
                worstes_indexs.append(k-1)
        
        for k in worstes_indexs:
            val = np.abs((f_row[k+1] - s_row[k+1]) * w[k])
            if val > d[i][j]:
                d[i][j] = val

print(d)

[[0.         1.15555556 0.86666667 1.44444444 0.57777778]
 [0.08       0.         0.08       0.28888889 0.08      ]
 [0.06222222 0.28888889 0.         0.57777778 0.01555556]
 [0.08       0.07777778 0.08       0.         0.08      ]
 [0.04666667 0.57777778 0.28888889 0.86666667 0.        ]]


In [7]:
c_v = np.amin(c, 1)
d_v = np.amax(d, 1)
print(decision_matrix)
print(c_v)
print(d_v)

[[2.   2.   0.8  0.8 ]
 [3.   6.   0.8  0.6 ]
 [4.   5.   0.6  0.8 ]
 [5.   7.   0.55 0.6 ]
 [6.   4.   0.65 0.8 ]]
[0.71111111 0.6        0.4        0.28888889 0.4       ]
[1.44444444 0.28888889 0.57777778 0.08       0.86666667]


In [8]:
c_core = 0.5
d_core = 0.5

c_indx = np.where(c_v > c_core, c_v, 0)
print(c_indx)
d_indx = np.where(d_v < d_core, d_v, 0)
print(d_indx)

rez = []
for i in range(len(c_indx)):
    if c_indx[i] != 0 and d_indx[i] != 0:
        rez.append(i)

print(decision_matrix[rez])


[0.71111111 0.6        0.         0.         0.        ]
[0.         0.28888889 0.         0.08       0.        ]
[[3.  6.  0.8 0.6]]
