In [15]:
import numpy as np
import numpy.ma as ma
import random as rnd
import itertools

In [14]:
alph = {
        'a' : 1, 
        'b' : 2, 
        'c' : 3, 
        'd' : 4, 
        'e' : 5, 
        'f' : 6, 
        'g' : 7, 
        'h' : 8, 
        'i' : 9, 
        'j' : 10, 
        'k' : 11, 
        'l' : 12, 
        'm' : 13, 
        'n' : 14, 
        'o' : 15, 
        'p' : 16, 
        'q' : 17, 
        'r' : 18, 
        's' : 19, 
        't' : 20, 
        'u' : 21, 
        'v' : 22, 
        'w' : 23, 
        'x' : 24, 
        'y' : 25, 
        'z' : 26
    }

t_1 = [0, alph['a'], alph['n'], alph['d'], alph['r']]

t_2 = [alph['a'], 0, alph['e'], alph['e'], alph['v']]

t_3 = [alph['n'], alph['e'], 0, alph['e'], alph['t']]

t_4 = [alph['d'], alph['e'], alph['e'], 0, alph['s']]

t_5 = [ alph['r'], alph['v'],alph['t'], alph['s'], 0]

tr_matrix = [t_1, t_2, t_3, t_4, t_5]

Greedy

In [9]:
def GredySearch(matrix, start_id = 0):
    path = []
    current_id = start_id
    for i in range(len(matrix)):
        min_id = FindMinIndex(matrix, current_id, path)
        path.append(current_id)
        current_id = min_id
    return path

def FindMinIndex(matrix,total_index, path):
    row = matrix[total_index]
    sub_row = np.copy(row)

    for i in path:
        sub_row[i] = 0

    minvalpos = np.argmin(ma.masked_where(sub_row==0, sub_row))  
    return minvalpos
    

In [10]:
def ExhaustiveSearch(matrix):
    base_path = np.arange(len(matrix))
    perm_set = itertools.permutations(base_path)
    best_path = np.arange(len(matrix))
    best_time = 1000
    worst_time = 0
    for i in perm_set:

        time = 0
        for j in range(len(i)):
            if j != len(i) - 1:
                time += tr_matrix[i[j]][i[j+1]]
            else:
                time += tr_matrix[i[j]][i[0]]
        if(time < best_time):
            best_time = time
            best_path = i
            best_path = np.append(best_path, i[0])
        if(time > worst_time):
            worst_time = time
    return (best_path, best_time, worst_time)
    

In [11]:
for k in range(5):
    gredyPath = GredySearch(tr_matrix, k)
    gredyPath.append(gredyPath[0])
    time = 0
    for i in range(len(gredyPath)-1):
        time += tr_matrix[gredyPath[i]][gredyPath[i+1]]

    print("if start is ", k, "id")
    print("time = ", time)
    print("patch= ", gredyPath)
    print()

if start is  0 id
time =  48
patch=  [0, 1, 2, 3, 4, 0]

if start is  1 id
time =  52
patch=  [1, 0, 3, 2, 4, 1]

if start is  2 id
time =  49
patch=  [2, 1, 0, 3, 4, 2]

if start is  3 id
time =  49
patch=  [3, 0, 1, 2, 4, 3]

if start is  4 id
time =  48
patch=  [4, 0, 1, 2, 3, 4]



In [12]:
(best_path, best_time, worst_time) = ExhaustiveSearch(tr_matrix)
print("best path: ", best_path)
print("best time: ", best_time)
print("worst time: ",  worst_time)


best path:  [0 1 2 3 4 0]
best time:  48
worst time:  65


In [16]:
def create_matrix_random(size):
    result_matrix_random = np.zeros((size, size))
    np.fill_diagonal(result_matrix_random, 34)

    for i in range(size):
        for j in range(size):
            if(j <= i - 1):
                result_matrix_random[i, j] = rnd.randint(1, 33)
                result_matrix_random[j, i] = result_matrix_random[i, j]

    print("Начальная матрица(random): ")
    print(result_matrix_random)
    return result_matrix_random

In [17]:
matr = create_matrix_random(10)
print(GredySearch(matr))

Начальная матрица(random): 
[[34.  5. 22.  6. 14.  8.  9. 27. 17. 16.]
 [ 5. 34.  3. 22.  8. 15. 14. 15. 27. 15.]
 [22.  3. 34. 16. 23. 10.  4. 18.  9. 27.]
 [ 6. 22. 16. 34.  1.  9. 29. 21. 24. 15.]
 [14.  8. 23.  1. 34.  3. 15. 20.  8. 26.]
 [ 8. 15. 10.  9.  3. 34. 29. 29. 25.  8.]
 [ 9. 14.  4. 29. 15. 29. 34. 31. 12. 28.]
 [27. 15. 18. 21. 20. 29. 31. 34. 12.  9.]
 [17. 27.  9. 24.  8. 25. 12. 12. 34. 24.]
 [16. 15. 27. 15. 26.  8. 28.  9. 24. 34.]]
[0, 1, 2, 6, 8, 4, 3, 5, 9, 7]
